import * as React from 'react';

export default function CountrySelect(wdtCol: any) {
  function defineWidth(wdtCol) {
    return `col-sm-${wdtCol} m-auto`;
  }
  return (
    <>
      <div className={defineWidth(wdtCol)}>
        <label className="form-control-placeholder" htmlFor="Country">
          País
        </label>
        <select
          id="campo-1032"
          className="form-control search_select input-edited"
          name="campo-1032"
        >
          <option value="6080">BRASIL</option>
          <option value="6081">Afeganistão</option>
          <option value="6082">África do Sul</option>
          <option value="6083">Albânia, República da</option>
          <option value="6084">Alemanha</option>
          <option value="6085">Andorra</option>
          <option value="6086">Angola</option>
          <option value="6087">Anguilla</option>
          <option value="6088">Antigua E Barbuda</option>
          <option value="6089">Antilhas Holandesas</option>
          <option value="6090">Arábia Saudita</option>
          <option value="6091">Argélia</option>
          <option value="6092">Argentina</option>
          <option value="6093">Armênia, República da</option>
          <option value="6094">Aruba</option>
          <option value="6095">Austrália</option>
          <option value="6096">Áustria</option>
          <option value="6097">Azerbaijão, República do</option>
          <option value="6098">Bahamas, Ilhas</option>
          <option value="6099">Bahrein, Ilhas</option>
          <option value="6100">Bangladesh</option>
          <option value="6101">Barbados</option>
          <option value="6102">Belarus, República da</option>
          <option value="6103">Bélgica</option>
          <option value="6104">Belize</option>
          <option value="6105">Benin</option>
          <option value="6106">Bermudas</option>
          <option value="6107">Bolívia</option>
          <option value="6108">Bosnia-Herzegovina (República da)</option>
          <option value="6109">Botsuana</option>
          <option value="6110">Brasil</option>
          <option value="6111">Brunei</option>
          <option value="6112">Bulgária, República da</option>
          <option value="6113">Burkina Faso</option>
          <option value="6114">Burundi</option>
          <option value="6115">Butão</option>
          <option value="6116">Cabo Verde, República de</option>
          <option value="6117">Camarões</option>
          <option value="6118">Camboja</option>
          <option value="6119">Canadá</option>
          <option value="6120">Canárias, Ilhas</option>
          <option value="6121">Catar</option>
          <option value="6122">Cayman, Ilhas</option>
          <option value="6123">Cazaquistao, República do</option>
          <option value="6124">Chade</option>
          <option value="6125">Chile</option>
          <option value="6126">China, República Popular</option>
          <option value="6127">Chipre</option>
          <option value="6128">Christmas,Ilhas (Navidad)</option>
          <option value="6129">Cingapura</option>
          <option value="6130">Cocos-Keeling, Ilhas</option>
          <option value="6131">Colômbia</option>
          <option value="6132">Comores, Ilhas</option>
          <option value="6133">Congo</option>
          <option value="6134">Congo, República Democrática do</option>
          <option value="6135">Cook, Ilhas</option>
          <option value="6136">Coréia, Rep.Pop.Democrática</option>
          <option value="6137">Coréia, República da</option>
          <option value="6138">Costa do Marfim</option>
          <option value="6139">Costa Rica</option>
          <option value="6140">Coveite</option>
          <option value="6141">Croácia, República da</option>
          <option value="6142">Cuba</option>
          <option value="6143">Delegação Especial da Palestina</option>
          <option value="6144">Dinamarca</option>
          <option value="6145">Djibuti</option>
          <option value="6146">Dominica, Ilha</option>
          <option value="6147">Egito</option>
          <option value="6148">El Salvador</option>
          <option value="6149">Emirados Árabes Unidos</option>
          <option value="6150">Equador</option>
          <option value="6151">Eritreia</option>
          <option value="6152">Eslovaca, República</option>
          <option value="6153">Eslovênia, República da</option>
          <option value="6154">Espanha</option>
          <option value="6155">Estados Unidos</option>
          <option value="6156">Estônia, República da</option>
          <option value="6157">Etiópia</option>
          <option value="6158">Falkland (Ilhas Malvinas)</option>
          <option value="6159">Feroe, Ilhas</option>
          <option value="6160">Fiji</option>
          <option value="6161">Filipinas</option>
          <option value="6162">Finlândia</option>
          <option value="6163">Formosa (Taiwan)</option>
          <option value="6164">França</option>
          <option value="6165">Gabão</option>
          <option value="6166">Gambia</option>
          <option value="6167">Gana</option>
          <option value="6168">Georgia, República da</option>
          <option value="6169">Gibraltar</option>
          <option value="6170">Granada</option>
          <option value="6171">Grécia</option>
          <option value="6172">Groenlândia</option>
          <option value="6173">Guadalupe</option>
          <option value="6174">Guam</option>
          <option value="6175">Guatemala</option>
          <option value="6176">Guiana</option>
          <option value="6177">Guiana Francesa</option>
          <option value="6178">Guiné</option>
          <option value="6179">Guiné-Bissau</option>
          <option value="6180">Guiné-Equatorial</option>
          <option value="6181">Haiti</option>
          <option value="6182">Honduras</option>
          <option value="6183">Hong Kong</option>
          <option value="6184">Hungria, República da</option>
          <option value="6185">Iemen</option>
          <option value="6186">Índia</option>
          <option value="6187">Indonésia</option>
          <option value="6188">Irã, República Islâmica do</option>
          <option value="6189">Iraque</option>
          <option value="6190">Irlanda</option>
          <option value="6191">Islândia</option>
          <option value="6192">Israel</option>
          <option value="6193">Itália</option>
          <option value="6194">Jamaica</option>
          <option value="6195">Japão</option>
          <option value="6196">Jersey, Ilha do Canal</option>
          <option value="6197">Johnston, Ilhas</option>
          <option value="6198">Jordânia</option>
          <option value="6199">Kiribati</option>
          <option value="6200">Laos, Rep.Pop.Democr.do</option>
          <option value="6201">Lebuan, Ilhas</option>
          <option value="6202">Lesoto</option>
          <option value="6203">Letônia, República da</option>
          <option value="6204">Líbano</option>
          <option value="6205">Libéria</option>
          <option value="6206">Líbia</option>
          <option value="6207">Liechtenstein</option>
          <option value="6208">Lituânia, República da</option>
          <option value="6209">Luxemburgo</option>
          <option value="6210">Macau</option>
          <option value="6211">Macedônia, Ant.Rep.Iugoslava</option>
          <option value="6212">Madagascar</option>
          <option value="6213">Madeira, Ilha da</option>
          <option value="6214">Malásia</option>
          <option value="6215">Malavi</option>
          <option value="6216">Maldivas</option>
          <option value="6217">Mali</option>
          <option value="6218">Malta</option>
          <option value="6219">Man, Ilha de</option>
          <option value="6220">Marianas do Norte</option>
          <option value="6221">Marrocos</option>
          <option value="6222">Marshall, Ilhas</option>
          <option value="6223">Martinica</option>
          <option value="6224">Maurício</option>
          <option value="6225">Mauritânia</option>
          <option value="6226">México</option>
          <option value="6227">Mianmar (Birmânia)</option>
          <option value="6228">Micronésia</option>
          <option value="6229">Midway, Ilhas</option>
          <option value="6230">Moçambique</option>
          <option value="6231">Moldavia, República da</option>
          <option value="6232">Mônaco</option>
          <option value="6233">Mongólia</option>
          <option value="6234">Montenegro</option>
          <option value="6235">Montserrat, Ilhas</option>
          <option value="6236">Namíbia</option>
          <option value="6237">Nauru</option>
          <option value="6238">Nepal</option>
          <option value="6239">Nicarágua</option>
          <option value="6240">Niger</option>
          <option value="6241">Nigéria</option>
          <option value="6242">Niue, Ilha</option>
          <option value="6243">Norfolk, Ilha</option>
          <option value="6244">Noruega</option>
          <option value="6245">Nova Caledônia</option>
          <option value="6246">Nova Zelândia</option>
          <option value="6247">Omã</option>
          <option value="6248">Pacífico, Ilhas do</option>
          <option value="6249">Países Baixos (Holanda)</option>
          <option value="6250">Palau</option>
          <option value="6251">Panamá</option>
          <option value="6252">Papua Nova Guiné</option>
          <option value="6253">Paquistão</option>
          <option value="6254">Paraguai</option>
          <option value="6255">Peru</option>
          <option value="6256">Pitcairn, Ilha De</option>
          <option value="6257">Polinésia Francesa</option>
          <option value="6258">Polônia, República da</option>
          <option value="6259">Porto Rico</option>
          <option value="6260">Portugal</option>
          <option value="6261">Quênia</option>
          <option value="6262">Quirguiz, República da</option>
          <option value="6263">Reino Unido</option>
          <option value="6264">República Centro-Africana</option>
          <option value="6265">República Dominicana</option>
          <option value="6266">Reunião, Ilha</option>
          <option value="6267">Romênia</option>
          <option value="6268">Ruanda</option>
          <option value="6269">Rússia, Federação da</option>
          <option value="6270">Saara Ocidental</option>
          <option value="6271">Salomão, Ilhas</option>
          <option value="6272">Samoa</option>
          <option value="6273">Samoa Americana</option>
          <option value="6274">San Marino</option>
          <option value="6275">Santa Helena</option>
          <option value="6276">Santa Lúcia</option>
          <option value="6277">Saint Kitts e Nevis</option>
          <option value="6278">São Cristovão e Neves, Ilhas</option>
          <option value="6279">São Pedro e Miquelon</option>
          <option value="6280">São Tomé e Príncipe, Ilhas</option>
          <option value="6281">São Vicente e Granadinas</option>
          <option value="6282">Senegal</option>
          <option value="6283">Serra Leoa</option>
          <option value="6284">Servia</option>
          <option value="6285">Seychelles</option>
          <option value="6286">Síria, República Árabe da</option>
          <option value="6287">Somália</option>
          <option value="6288">Sri Lanka</option>
          <option value="6289">Suazilândia</option>
          <option value="6290">Sudão</option>
          <option value="6291">Suécia</option>
          <option value="6292">Suíça</option>
          <option value="6293">Suriname</option>
          <option value="6294">Tadjiquistão, República do</option>
          <option value="6295">Tailândia</option>
          <option value="6296">Tanzania, Rep. Unida da</option>
          <option value="6297">Tcheca, República</option>
          <option value="6298">Território Britânico no Oceano Índico</option>
          <option value="6299">Timor Leste</option>
          <option value="6300">Togo</option>
          <option value="6301">Tonga</option>
          <option value="6302">Toquelau, Ilhas</option>
          <option value="6303">Trinidad e Tobago</option>
          <option value="6304">Tunísia</option>
          <option value="6305">Turcas e Caicos, Ilhas</option>
          <option value="6306">Turcomenistão, República do</option>
          <option value="6307">Turquia</option>
          <option value="6308">Tuvalu</option>
          <option value="6309">Ucrânia</option>
          <option value="6310">Uganda</option>
          <option value="6311">Uruguai</option>
          <option value="6312">Uzbequistão, República do</option>
          <option value="6313">Vanuatu</option>
          <option value="6314">Vaticano, Est. da Cidade do</option>
          <option value="6315">Venezuela</option>
          <option value="6316">Vietnã</option>
          <option value="6317">Virgens, Ilhas (Britânicas)</option>
          <option value="6318">Virgens, Ilhas (E.U.A.)</option>
          <option value="6319">Wake, Ilha</option>
          <option value="6320">Wallis e Futuna, Ilhas</option>
          <option value="6321">Zâmbia</option>
          <option value="6322">Zimbabue</option>
        </select>
      </div>
    </>
  );
}
