import React from 'react';
import Select from 'react-select';

interface SelectCountryArgs {
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

export default function SelectCountry({ onChange }: SelectCountryArgs) {
  const options = [
    { value: '6080', label: 'Brasil' },
    { value: '6081', label: 'Afeganistão' },
    { value: '6082', label: 'África do Sul' },
    { value: '6083', label: 'Albânia, República da' },
    { value: '6084', label: 'Alemanha' },
    { value: '6085', label: 'Andorra' },
    { value: '6086', label: 'Angola' },
    { value: '6087', label: 'Anguilla' },
    { value: '6088', label: 'Antigua E Barbuda' },
    { value: '6089', label: 'Antilhas Holandesas' },
    { value: '6090', label: 'Arábia Saudita' },
    { value: '6091', label: 'Argélia' },
    { value: '6092', label: 'Argentina' },
    { value: '6093', label: 'Armênia, República da' },
    { value: '6094', label: 'Aruba' },
    { value: '6095', label: 'Austrália' },
    { value: '6096', label: 'Áustria' },
    { value: '6097', label: 'Azerbaijão, República do' },
    { value: '6098', label: 'Bahamas, Ilhas' },
    { value: '6099', label: 'Bahrein, Ilhas' },
    { value: '6100', label: 'Bangladesh' },
    { value: '6101', label: 'Barbados' },
    { value: '6102', label: 'Belarus, República da' },
    { value: '6103', label: 'Bélgica' },
    { value: '6104', label: 'Belize' },
    { value: '6105', label: 'Benin' },
    { value: '6106', label: 'Bermudas' },
    { value: '6107', label: 'Bolívia' },
    { value: '6108', label: 'Bosnia-Herzegovina (República da)' },
    { value: '6109', label: 'Botsuana' },
    { value: '6111', label: 'Brunei' },
    { value: '6112', label: 'Bulgária, República da' },
    { value: '6113', label: 'Burkina Faso' },
    { value: '6114', label: 'Burundi' },
    { value: '6115', label: 'Butão' },
    { value: '6116', label: 'Cabo Verde, República de' },
    { value: '6117', label: 'Camarões' },
    { value: '6118', label: 'Camboja' },
    { value: '6119', label: 'Canadá' },
    { value: '6120', label: 'Canárias, Ilhas' },
    { value: '6121', label: 'Catar' },
    { value: '6122', label: 'Cayman, Ilhas' },
    { value: '6123', label: 'Cazaquistao, República do' },
    { value: '6124', label: 'Chade' },
    { value: '6125', label: 'Chile' },
    { value: '6126', label: 'China, República Popular' },
    { value: '6127', label: 'Chipre' },
    { value: '6128', label: 'Christmas,Ilhas (Navidad)' },
    { value: '6129', label: 'Cingapura' },
    { value: '6130', label: 'Cocos-Keeling, Ilhas' },
    { value: '6131', label: 'Colômbia' },
    { value: '6132', label: 'Comores, Ilhas' },
    { value: '6133', label: 'Congo' },
    { value: '6134', label: 'Congo, República Democrática do' },
    { value: '6135', label: 'Cook, Ilhas' },
    { value: '6136', label: 'Coréia, Rep.Pop.Democrática' },
    { value: '6137', label: 'Coréia, República da' },
    { value: '6138', label: 'Costa do Marfim' },
    { value: '6139', label: 'Costa Rica' },
    { value: '6140', label: 'Coveite' },
    { value: '6141', label: 'Croácia, República da' },
    { value: '6142', label: 'Cuba' },
    { value: '6143', label: 'Delegação Especial da Palestina' },
    { value: '6144', label: 'Dinamarca' },
    { value: '6145', label: 'Djibuti' },
    { value: '6146', label: 'Dominica, Ilha' },
    { value: '6147', label: 'Egito' },
    { value: '6148', label: 'El Salvador' },
    { value: '6149', label: 'Emirados Árabes Unidos' },
    { value: '6150', label: 'Equador' },
    { value: '6151', label: 'Eritreia' },
    { value: '6152', label: 'Eslovaca, República' },
    { value: '6153', label: 'Eslovênia, República da' },
    { value: '6154', label: 'Espanha' },
    { value: '6155', label: 'Estados Unidos' },
    { value: '6156', label: 'Estônia, República da' },
    { value: '6157', label: 'Etiópia' },
    { value: '6158', label: 'Falkland (Ilhas Malvinas)' },
    { value: '6159', label: 'Feroe, Ilhas' },
    { value: '6160', label: 'Fiji' },
    { value: '6161', label: 'Filipinas' },
    { value: '6162', label: 'Finlândia' },
    { value: '6163', label: 'Formosa (Taiwan)' },
    { value: '6164', label: 'França' },
    { value: '6165', label: 'Gabão' },
    { value: '6166', label: 'Gambia' },
    { value: '6167', label: 'Gana' },
    { value: '6168', label: 'Georgia, República da' },
    { value: '6169', label: 'Gibraltar' },
    { value: '6170', label: 'Granada' },
    { value: '6171', label: 'Grécia' },
    { value: '6172', label: 'Groenlândia' },
    { value: '6173', label: 'Guadalupe' },
    { value: '6174', label: 'Guam' },
    { value: '6175', label: 'Guatemala' },
    { value: '6176', label: 'Guiana' },
    { value: '6177', label: 'Guiana Francesa' },
    { value: '6178', label: 'Guiné' },
    { value: '6179', label: 'Guiné-Bissau' },
    { value: '6180', label: 'Guiné-Equatorial' },
    { value: '6181', label: 'Haiti' },
    { value: '6182', label: 'Honduras' },
    { value: '6183', label: 'Hong Kong' },
    { value: '6184', label: 'Hungria, República da' },
    { value: '6185', label: 'Iemen' },
    { value: '6186', label: 'Índia' },
    { value: '6187', label: 'Indonésia' },
    { value: '6188', label: 'Irã, República Islâmica do' },
    { value: '6189', label: 'Iraque' },
    { value: '6190', label: 'Irlanda' },
    { value: '6191', label: 'Islândia' },
    { value: '6192', label: 'Israel' },
    { value: '6193', label: 'Itália' },
    { value: '6194', label: 'Jamaica' },
    { value: '6195', label: 'Japão' },
    { value: '6196', label: 'Jersey, Ilha do Canal' },
    { value: '6197', label: 'Johnston, Ilhas' },
    { value: '6198', label: 'Jordânia' },
    { value: '6199', label: 'Kiribati' },
    { value: '6200', label: 'Laos, Rep.Pop.Democr.do' },
    { value: '6201', label: 'Lebuan, Ilhas' },
    { value: '6202', label: 'Lesoto' },
    { value: '6203', label: 'Letônia, República da' },
    { value: '6204', label: 'Líbano' },
    { value: '6205', label: 'Libéria' },
    { value: '6206', label: 'Líbia' },
    { value: '6207', label: 'Liechtenstein' },
    { value: '6208', label: 'Lituânia, República da' },
    { value: '6209', label: 'Luxemburgo' },
    { value: '6210', label: 'Macau' },
    { value: '6211', label: 'Macedônia, Ant.Rep.Iugoslava' },
    { value: '6212', label: 'Madagascar' },
    { value: '6213', label: 'Madeira, Ilha da' },
    { value: '6214', label: 'Malásia' },
    { value: '6215', label: 'Malavi' },
    { value: '6216', label: 'Maldivas' },
    { value: '6217', label: 'Mali' },
    { value: '6218', label: 'Malta' },
    { value: '6219', label: 'Man, Ilha de' },
    { value: '6220', label: 'Marianas do Norte' },
    { value: '6221', label: 'Marrocos' },
    { value: '6222', label: 'Marshall, Ilhas' },
    { value: '6223', label: 'Martinica' },
    { value: '6224', label: 'Maurício' },
    { value: '6225', label: 'Mauritânia' },
    { value: '6226', label: 'México' },
    { value: '6227', label: 'Mianmar (Birmânia)' },
    { value: '6228', label: 'Micronésia' },
    { value: '6229', label: 'Midway, Ilhas' },
    { value: '6230', label: 'Moçambique' },
    { value: '6231', label: 'Moldavia, República da' },
    { value: '6232', label: 'Mônaco' },
    { value: '6233', label: 'Mongólia' },
    { value: '6234', label: 'Montenegro' },
    { value: '6235', label: 'Montserrat, Ilhas' },
    { value: '6236', label: 'Namíbia' },
    { value: '6237', label: 'Nauru' },
    { value: '6238', label: 'Nepal' },
    { value: '6239', label: 'Nicarágua' },
    { value: '6240', label: 'Niger' },
    { value: '6241', label: 'Nigéria' },
    { value: '6242', label: 'Niue, Ilha' },
    { value: '6243', label: 'Norfolk, Ilha' },
    { value: '6244', label: 'Noruega' },
    { value: '6245', label: 'Nova Caledônia' },
    { value: '6246', label: 'Nova Zelândia' },
    { value: '6247', label: 'Omã' },
    { value: '6248', label: 'Pacífico, Ilhas do' },
    { value: '6249', label: 'Países Baixos (Holanda)' },
    { value: '6250', label: 'Palau' },
    { value: '6251', label: 'Panamá' },
    { value: '6252', label: 'Papua Nova Guiné' },
    { value: '6253', label: 'Paquistão' },
    { value: '6254', label: 'Paraguai' },
    { value: '6255', label: 'Peru' },
    { value: '6256', label: 'Pitcairn, Ilha De' },
    { value: '6257', label: 'Polinésia Francesa' },
    { value: '6258', label: 'Polônia, República da' },
    { value: '6259', label: 'Porto Rico' },
    { value: '6260', label: 'Portugal' },
    { value: '6261', label: 'Quênia' },
    { value: '6262', label: 'Quirguiz, República da' },
    { value: '6263', label: 'Reino Unido' },
    { value: '6264', label: 'República Centro-Africana' },
    { value: '6265', label: 'República Dominicana' },
    { value: '6266', label: 'Reunião, Ilha' },
    { value: '6267', label: 'Romênia' },
    { value: '6268', label: 'Ruanda' },
    { value: '6269', label: 'Rússia, Federação da' },
    { value: '6270', label: 'Saara Ocidental' },
    { value: '6271', label: 'Salomão, Ilhas' },
    { value: '6272', label: 'Samoa' },
    { value: '6273', label: 'Samoa Americana' },
    { value: '6274', label: 'San Marino' },
    { value: '6275', label: 'Santa Helena' },
    { value: '6276', label: 'Santa Lúcia' },
    { value: '6277', label: 'Saint Kitts e Nevis' },
    { value: '6278', label: 'São Cristovão e Neves, Ilhas' },
    { value: '6279', label: 'São Pedro e Miquelon' },
    { value: '6280', label: 'São Tomé e Príncipe, Ilhas' },
    { value: '6281', label: 'São Vicente e Granadinas' },
    { value: '6282', label: 'Senegal' },
    { value: '6283', label: 'Serra Leoa' },
    { value: '6284', label: 'Servia' },
    { value: '6285', label: 'Seychelles' },
    { value: '6286', label: 'Síria, República Árabe da' },
    { value: '6287', label: 'Somália' },
    { value: '6288', label: 'Sri Lanka' },
    { value: '6289', label: 'Suazilândia' },
    { value: '6290', label: 'Sudão' },
    { value: '6291', label: 'Suécia' },
    { value: '6292', label: 'Suíça' },
    { value: '6293', label: 'Suriname' },
    { value: '6294', label: 'Tadjiquistão, República do' },
    { value: '6295', label: 'Tailândia' },
    { value: '6296', label: 'Tanzania, Rep. Unida da' },
    { value: '6297', label: 'Tcheca, República' },
    { value: '6298', label: 'Território Britânico no Oceano Índico' },
    { value: '6299', label: 'Timor Leste' },
    { value: '6300', label: 'Togo' },
    { value: '6301', label: 'Tonga' },
    { value: '6302', label: 'Toquelau, Ilhas' },
    { value: '6303', label: 'Trinidad e Tobago' },
    { value: '6304', label: 'Tunísia' },
    { value: '6305', label: 'Turcas e Caicos, Ilhas' },
    { value: '6306', label: 'Turcomenistão, República do' },
    { value: '6307', label: 'Turquia' },
    { value: '6308', label: 'Tuvalu' },
    { value: '6309', label: 'Ucrânia' },
    { value: '6310', label: 'Uganda' },
    { value: '6311', label: 'Uruguai' },
    { value: '6312', label: 'Uzbequistão, República do' },
    { value: '6313', label: 'Vanuatu' },
    { value: '6314', label: 'Vaticano, Est. da Cidade do' },
    { value: '6315', label: 'Venezuela' },
    { value: '6316', label: 'Vietnã' },
    { value: '6317', label: 'Virgens, Ilhas (Britânicas)' },
    { value: '6318', label: 'Virgens, Ilhas (E.U.A.)' },
    { value: '6319', label: 'Wake, Ilha' },
    { value: '6320', label: 'Wallis e Futuna, Ilhas' },
    { value: '6321', label: 'Zâmbia' },
    { value: '6322', label: 'Zimbabue' },
  ];

  return <Select options={options} onChange={onChange} />;
}
